import React, { useState } from "react";
import { type NextPage } from "next";
import Head from "next/head";
import Commitment from "../components/About/Commitment";
import Headquarters from "../components/About/Headquarters";
import Hero from "../components/About/Hero";
import Quality from "../components/About/Quality";
import Footer from "../components/Home/Footer";
import Navbar from "../components/UI/Navbar";

const About: NextPage = () => {
  const [showModal, setShowModal] = useState(false);
  return (
    <>
      <Head>
        <title>About Us</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar setShowModal={setShowModal} showModal={showModal} />
      <main className="container mx-auto w-full  max-w-8xl bg-lightCream">
        <Hero />
        {!showModal && (
          <>
            <Commitment />
            <Quality />
            <Headquarters />
          </>
        )}
      </main>
      {!showModal && (
        <>
          <div className="mt-[120px] md:mt-36">
            <Footer />
          </div>
        </>
      )}
    </>
  );
};

export default About;
