import React, { useState, useEffect } from "react";
import { type NextPage } from "next";
import Head from "next/head";
import CoffeeDrinks from "../components/Subscribe/Coffee/Coffee";
import type { TOrderSummary } from "../components/Subscribe/Coffee/Coffee";

import Hero from "../components/Subscribe/Hero";
import PlanDetails from "../components/Subscribe/PlanDetails";
import Navbar from "../components/UI/Navbar";
import Footer from "../components/Home/Footer";
import SummaryModal from "../components/Subscribe/Coffee/SummaryModal";

const Subscribe: NextPage = () => {
  const [selected, setSelected] = useState(0);
  const [showModal, setShowModal] = useState(false);
  const [showSummary, setShowSummary] = useState(false);

  useEffect(() => {
    const body = document.querySelector("body");
    if (showSummary) {
      body?.classList.add("overflow-hidden");
    } else {
      body?.classList.remove("overflow-hidden");
    }
  }, [showSummary]);

  const [orderPhrase, setOrderPhrase] = useState<TOrderSummary>({
    preference: "Capsule",
    beanType: "Single Origin",
    quantity: "250g",
    grind: "Wholebean",
    delivery: "Every week",
  });

  const handleOrder = (orderType: string, order: string, index: number) => {
    setSelected(index);
    setOrderPhrase((prev) => ({ ...prev, [orderType]: order }));
    console.log(orderPhrase);
  };

  return (
    <>
      <Head>
        <title>Subscribe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar setShowModal={setShowModal} showModal={showModal} />
      <main className="container mx-auto  w-full max-w-8xl overflow-hidden bg-lightCream">
        <Hero />
        {!showSummary && (
          <>
            {!showModal && (
              <>
                <PlanDetails />
                <CoffeeDrinks
                  handleOrder={handleOrder}
                  selected={selected}
                  setOrderPhrase={setOrderPhrase}
                  orderPhrase={orderPhrase}
                  setShowSummary={setShowSummary}
                />
              </>
            )}
          </>
        )}
        {showSummary && (
          <SummaryModal summary={orderPhrase} setShowSummary={setShowSummary} />
        )}
      </main>
      {!showModal && !showSummary && <Footer />}
    </>
  );
};

export default Subscribe;
